version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
      #image: amirpourmand/al-folio
    build:
        context: .
        dockerfile: Dockerfile
    network_mode: host
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
